seed: 1
inp_size: 48
batch_size: 2
total_batch_size: 2
epoch_max:  500 
epoch_save: 100
queue_size: 2048

blur:
  # Degradation specifications
  noise: 0.0

train_dataset1:
  dataset:
    name: image-volume
    args:
      root_path: D:\data\cremi_A.tif
      repeat: 10
  wrapper:
    name: sr-degrade
    args:
      inp_size: 48
      augment: true
      scale: 8

optimizer:
  name: adam
  args:
   lr: 0.03
   weight_decay: 0 

degrade:
  name: simsiam
  args:
    dim: 256
    pred_dim: 512


data_norm:
  inp: {sub: [0.5], div: [0.5]}
