batch_size: 1
test_dataset:
  dataset:
    name: image-test
    args:
      root_path: /your/path/to/test/volume.tif
      direction: yz
      scale: 10

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

  
  
