seed: 10
batch_size: 2
total_batch_size: 2
sample_q: 2304
num_pt: 7
inp_size: 48
queue_size: 320

lambda_geom: 0.1 

train_dataset1: # data set setting.
  dataset: # the module responsible for loading image.
    name: image-volume
    args:
      root_path: /your/path/to/data.tif # volume data path.
      sdf_path: /your/path/to/sdf.tif # sdf data path.
      repeat: 8 # images in dataset will be loaded 10 times.
  wrapper: # the module responsible for preprocessing image.
    name: sr-gaussian
    args:
      inp_size: 48 # input_size will be 48 * (48 * scale)
      sample_q: 2304 # number of pixels to predict for one slice.
      augment: true # data augment.
      scale: 8 # reconstruction factor.

val_dataset1:
  dataset:
    name: image-volume
    args:
      root_path: /your/path/to/val-data.tif
      sdf_path: /your/path/to/val_sdf_data.tif
  wrapper:
    name: sr-gaussian
    args:
      inp_size: 48
      sample_q: 2304
      scale: 8

data_norm: # set data range form [0,1] to [-1, 1].
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

sdf_norm: # set sdf range form [0,1] to [-1, 1].
  sub: [0.0]  # should replace the mean and std of sdf.
  div: [1.0] 

optimizer: # optimizer setting
  name: adam
  args:
   lr: 1.e-4

multi_step_lr: # update strategy of learning rate for training.
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_max: 1000 # number of training epoch.
epoch_val: 1 # epoch interval for testing on valid set.
epoch_save: 300 # epoch interval for saving checkpoints.

model: # model setting
  name: models
  args: {}
  SR: # inr model setting
    name: liif
    args:
      encoder_spec:   # feature extractor.
        name: rdn
        args:
          no_upsampling: true
      imnet_spec: # implicit degradation predictor.
        name: mlp
        args:
          out_dim: 1
          hidden_list: [256, 256, 256, 256]
  degrade: # degradation predictor model setting.
    name: simsiam
    args:
      dim: 256
  path: checkpoints/degrade/EPFL/epoch-best.pth # the save path of degradation predictor.





  
  
